git:
  branch: main
  repo: ""
  host: ""

image:
  dockerfile: ./Dockerfile
  dockerfileUI: ./chat-ui/Dockerfile
  registry: ""
  organization: ""
  host: ""
  name: ""
  nameUI: ""
  tag: ""
  password: ""

cluster:
  subdomain:
